"""add image_path to recipes

Revision ID: 0bbcc0b473be
Revises: b1c3fed69eaa
Create Date: 2026-08-07 14:19:29.225039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbcc0b473be'
down_revision: Union[str, Sequence[str], None] = 'b1c3fed69eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image_path')
    # ### end Alembic commands ###
