"""avaliacao por estrelas

Revision ID: 1124746a9f09
Revises: 514ada9a40d4
Create Date: 2026-08-11 14:31:35.644066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1124746a9f09'
down_revision: Union[str, Sequence[str], None] = '514ada9a40d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # Defesa em profundidade — a validação 1-5 já existe em
    # schemas.RecipeRatingIn (Pydantic), isto só garante que nenhum outro
    # caminho (script, correção manual) consegue gravar um valor fora do
    # intervalo.
    op.create_check_constraint("ck_recipes_rating_range", "recipes", "rating IS NULL OR rating BETWEEN 1 AND 5")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_recipes_rating_range", "recipes", type_="check")
    op.drop_column('recipes', 'rating')
    # ### end Alembic commands ###
