"""comentarios por receita

Revision ID: 49f829cb42e3
Revises: 1124746a9f09
Create Date: 2026-08-11 14:37:30.080940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f829cb42e3'
down_revision: Union[str, Sequence[str], None] = '1124746a9f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTA: o autogenerate também propôs op.drop_constraint('ck_recipes_
    # rating_range', ...) — falso positivo, o CHECK não está declarado no
    # modelo SQLAlchemy (só existe na migração 1124746a9f09), mesmo padrão
    # do índice GIN documentado em models.py::Recipe (já aconteceu com
    # índices, agora com um CHECK). Removido à mão para não apagar a
    # validação de intervalo do rating na BD.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
