"""favoritos por utilizador

Revision ID: 514ada9a40d4
Revises: b1d85af98dd0
Create Date: 2026-08-11 14:27:45.231437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514ada9a40d4'
down_revision: Union[str, Sequence[str], None] = 'b1d85af98dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_favorites',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'user_id')
    )
    # Dado a preservar: o favorito era do agregado (visível aos dois
    # utilizadores), não de uma pessoa — migrar para "favoritado por todos
    # os membros atuais da workspace dessa receita" é a leitura mais fiel ao
    # comportamento anterior, em vez de simplesmente perder a informação.
    op.execute(
        """
        INSERT INTO recipe_favorites (recipe_id, user_id)
        SELECT r.id, wm.user_id
        FROM recipes r
        JOIN workspace_members wm ON wm.workspace_id = r.workspace_id
        WHERE r.is_favorite IS TRUE
        """
    )
    op.drop_column('recipes', 'is_favorite')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.execute(
        """
        UPDATE recipes SET is_favorite = TRUE
        WHERE id IN (SELECT DISTINCT recipe_id FROM recipe_favorites)
        """
    )
    op.drop_table('recipe_favorites')
    # ### end Alembic commands ###
