"""add share_token and share_expires_at to recipes

Revision ID: 5d7092e277e3
Revises: eb74e97da107
Create Date: 2026-08-12 22:14:30.605625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d7092e277e3'
down_revision: Union[str, Sequence[str], None] = 'eb74e97da107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('share_token', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('share_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'recipes', ['share_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='unique')
    op.drop_column('recipes', 'share_expires_at')
    op.drop_column('recipes', 'share_token')
    # ### end Alembic commands ###
