"""add manual nutrition fields to recipes

Revision ID: 8044bc24ade0
Revises: 0bbcc0b473be
Create Date: 2026-08-07 14:35:44.018200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8044bc24ade0'
down_revision: Union[str, Sequence[str], None] = '0bbcc0b473be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('calories_kcal', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('protein_g', sa.Numeric(precision=6, scale=1), nullable=True))
    op.add_column('recipes', sa.Column('carbs_g', sa.Numeric(precision=6, scale=1), nullable=True))
    op.add_column('recipes', sa.Column('fat_g', sa.Numeric(precision=6, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'fat_g')
    op.drop_column('recipes', 'carbs_g')
    op.drop_column('recipes', 'protein_g')
    op.drop_column('recipes', 'calories_kcal')
    # ### end Alembic commands ###
