"""custo estimado da receita

Revision ID: 90e07c148e15
Revises: a1ded7dbab02
Create Date: 2026-08-11 16:22:53.075051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e07c148e15'
down_revision: Union[str, Sequence[str], None] = 'a1ded7dbab02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('estimated_cost', sa.Numeric(precision=8, scale=2), nullable=True))
    # NOTA: falso positivo do autogenerate removido à mão (CHECK do rating,
    # ver models.py::Recipe.rating — já a quinta vez).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'estimated_cost')
    # ### end Alembic commands ###
