"""despensa basica

Revision ID: a1ded7dbab02
Revises: 8f63280c8233
Create Date: 2026-08-11 16:04:30.382904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ded7dbab02'
down_revision: Union[str, Sequence[str], None] = '8f63280c8233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('has_it', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_pantry_item_workspace_name')
    )
    # NOTA: falso positivo do autogenerate removido à mão (CHECK do rating,
    # ver models.py::Recipe.rating — já a quarta vez).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pantry_items')
    # ### end Alembic commands ###
