"""add is_header to ingredients

Revision ID: b1c3fed69eaa
Revises: 93c380aef9a6
Create Date: 2026-08-07 14:05:29.497520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c3fed69eaa'
down_revision: Union[str, Sequence[str], None] = '93c380aef9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('is_header', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'is_header')
    # ### end Alembic commands ###
