"""add last_made_at to recipes

Revision ID: d55bbdb8e942
Revises: 8044bc24ade0
Create Date: 2026-08-07 17:05:03.486953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55bbdb8e942'
down_revision: Union[str, Sequence[str], None] = '8044bc24ade0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('last_made_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'last_made_at')
    # ### end Alembic commands ###
